"""empty message

Revision ID: 7200c295bff9
Revises: 2c9bc9a23880
Create Date: 2021-04-28 01:00:55.846204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7200c295bff9'
down_revision = '2c9bc9a23880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertypes', sa.Column('Position', sa.String(length=10), nullable=False))
    op.drop_constraint('usertypes_Name_key', 'usertypes', type_='unique')
    op.create_unique_constraint(None, 'usertypes', ['Position'])
    op.drop_column('usertypes', 'Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertypes', sa.Column('Name', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usertypes', type_='unique')
    op.create_unique_constraint('usertypes_Name_key', 'usertypes', ['Name'])
    op.drop_column('usertypes', 'Position')
    # ### end Alembic commands ###
